### PR TITLE
Updated Foxit Reader

### PR DESCRIPTION
**Pull request by ComFreek**
Things to do:

- [ ] @alanstevens Could you check the registry paths at your mashine, please? Are they the same?
- [ ] Is the registry path for 32-bit Windows correct? I don't have a running system with 32-bit Windows.
- [ ] Change the icon's path in the nuspec file to your repository. This is trivial once this PR is merged.

### CODE REVIEW

**Comment by ComFreek** [comment]
@alanstevens Have you had a chance to review the PR?

**Comment by ComFreek** [comment]
FYI: I pushed an update on my own.

**Comment by mew1033** [comment]
I never had a chance to review this, but I can go ahead and merge it if you'd like. It sounds like you pushed it to chocolatey.org already, and it looks like it's working, so I have no qualms about merging it here.
Are you going to be maintaining a separate repo for foxit?
@alanstevens might be able to make you a contributor here so you can just push updates whenever you want.

**Comment by ComFreek** [comment]
General note: This PR is outdated anyway. A recent version can be accessed from my [ComFreek/chocolatey-packages](https://github.com/ComFreek/chocolatey-packages). I am currently working on an automatic package.

> Are you going to be maintaining a separate repo for foxit?

The main goal should be to have the packages always updated and maintained. It doesn't matter to me where the actual repo is located as long as PRs are quickly merged and reviewed.
How many active contributors are there for this repo?

Unfortunately, the repo owner @alanstevens has not yet replied to this [PR](https://github.com/alanstevens/ChocoPackages/pull/63#issue-53414819) and to the [filed issue](https://github.com/alanstevens/ChocoPackages/issues/62#issue-53224764) which (frankly speaking - if I may) discourages me a little bit from maintaining the code in this repo.

I apologize for not having pinged you in this PR. I *somehow* thought you were alanstevens.

**Comment by mew1033** [comment]
Perhaps an automatic package? I haven't made one before, but I plan on doing so soon.

Frankly, I think you should be added as a contributor to this repo so you can just push updates when you make them. I submitted a PR for a few packages and was eventually added as a contributor. Now when I update them, I just push straight to the repo.
If you'd like to keep Foxit in your own repo, I don't think @alanstevens would mind, however I think there should only be one. If there are multiple repos, things could get confusing fast.

**Comment by ComFreek** [comment]
An automatic package would be extremely nice. I am currently working on one for NetBeans.

> If you'd like to keep Foxit in your own repo
The only "fear" I have is that the package could become outdated. An automatic package would definitely alleviate this problem.

(Please don't get me wrong, I don't want to protect my repo from being copied or modified in forks. Being able to ensure that the package is updated is my main goal.)

> If there are multiple repos, things could get confusing fast.
:+1: Agreed.

I guess we have to wait for an answer from alanstevens.

**Comment by ComFreek** [comment]
@mew1033 I hope you haven't already started to work on an automatic package since I have just created one. See https://github.com/ComFreek/chocolatey-packages/tree/master/automatic (`foxitreader.xml` is the exported settings file from Ketarin).

**Comment by mew1033** [comment]
Awesome! I definitely think automatic packages are the way to go. My vote now is for @alanstevens to remove foxit reader from his repo here. Perhaps he should point it over to your package. I would do it,  but I don't know if he wants me completely removing packages from his repo.

**Comment by alanstevens** [comment]
It sounds like you have things well in hand, @ComFreek. I'll remove Foxit from this repo.

**Pull request closed without merging**
